# Generated by Django 3.1.7 on 2021-03-09 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='post',
            new_name='message',
        ),
    ]
